version: "3.9"

services:
  db: 
    image: postgres 
    restart: always 
    environment: 
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      POSTGRES_DB: ${PSQL_DATABASE}

  tailwind:
    build:
      context: ./tailwind
      dockerfile: Dockerfile
    tty: true
    restart: always
    volumes:
      - ./tailwind:/src
      - ./assets:/dst
      - ./templates:/templates
