version: "3.9"

services:
  server:
    build:
      context: ./
      dockerfile: go.prod.Dockerfile
    restart: always
    volumes:
      - ./assets:/assets
      - ./images:/images
      - .env:/.env
    # ports:
    #   - 3000:3000
    depends_on:
      - db

  caddy:
    image: caddy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
